### ISSUE TITLE
Error when using SLO with Backend Prometheus

### ISSUE THREAD

**Issue by svenmueller** [terraform-google-modules/terraform-google-slo#42]
I get an error when using an SLO with backend class "Prometheus".  

```
---
service_name:      product
feature_name:      search
slo_name:          freshness
slo_description:   95% of messages in queue are fresh
slo_target:        0.95
backend:
  class:           Prometheus
  method:          good_bad_ratio
  url:             ${prometheus_url}
  measurement:
    filter_good:  <query-1>
    filter_valid:  <query-2>
exporters:
- class:           Stackdriver
  project_id:      ${stackdriver_host_project_id}
```

Error when running TF (missing field changes with each run):

```
Error: Invalid value for module argument

  on main.tf line 130, in module "product_search_freshness":
 130:   config                     = local.slo_config_map["product-search-freshness"]

The given value is not suitable for child module variable "config" defined at
.terraform/modules/product_search_freshness/modules/slo/variables.tf:41,1-18:
attribute "slo_target": number required.
```

Somehow looks like there is an issue with the YAML? When i output the configmap in TF, i can see the SLO with all it's fields from the file.

```
output "product_search_freshness" {
  value = local.slo_config_map["product-search-freshness"]
}
```

TF output:
```
product_search_freshness = {
  "backend" = {
    "class" = "Prometheus"
    "measurement" = {
      "filter_good" = "query-1"
      "filter_valid" = "query-2"
    }
    "method" = "good_bad_ratio"
    "url" = "https://prometheus.com/"
  }
  "exporters" = [
    {
      "class" = "Pubsub"
      "project_id" = "my-project-id"
      "topic_name" = "slo-export-topic"
    },
  ]
  "feature_name" = "search"
  "service_name" = "product"
  "slo_description" = "95% of messages in queue are fresh"
  "slo_name" = "freshness"
  "slo_target" = 0.95
}
```

Any idea what can be wrong here?

Thx Sven

**Comment by ocervell** [comment]
Does it run with the `slo-generator` CLI ? It seems that it's a malformed YAML but I'm don't see anything wrong with it. Which version of TF are you using ?

**Comment by palladius** [comment]
The given value is not suitable for child module variable "config" defined at
    .terraform/modules/product_search_freshness/modules/slo/variables.tf:41,1-18:
    attribute "slo_target": number required.

Strange indeed, 0.95 should be parsed as float from YAML. Just for troubleshooting, have you tried changing to 1?

https://symfony.com/doc/current/components/yaml/yaml_format.html#numbers

Maybe TF  somehow converts the float to string?

**Comment by ocervell** [comment]
@palladius weird, the examples in [https://github.com/terraform-google-modules/terraform-google-slo/blob/master/examples/slo-generator/yaml_example/templates/](https://github.com/terraform-google-modules/terraform-google-slo/blob/master/examples/slo-generator/yaml_example/templates/) use floats and they're converting okay.

**Comment by ocervell** [comment]
Ok, found the error: it seems like the `backend` block requires a `project_id` field, and Terraform is trying to enforce that. Please add a `project_id` field to your `backend` section and it should work:

```
---
service_name:      product
feature_name:      search
slo_name:          freshness
slo_description:   95% of messages in queue are fresh
slo_target:        0.95
backend:
  class:           Prometheus
  method:          good_bad_ratio
  project_id:      test
  url:             ${prometheus_url}
  measurement:
    filter_good:  <query-1>
    filter_valid:  <query-2>
exporters:
- class:           Stackdriver
  project_id:      ${stackdriver_host_project_id}
```

Since Prometheus does not have a `project_id` per say, we need to remove this requirement for this type of backend.

It's worth noting that Terraform error is really wrong here, and that there is nothing wrong with the YAML or the `slo_target` number ...

**Comment by ocervell** [comment]
This PR is the fix to avoid having to specify the useless `project_id`: https://github.com/terraform-google-modules/terraform-google-slo/pull/43

**Comment by svenmueller** [comment]
Thx Olivier, i will give it a try! For reference, this is the stacktrace i get when running the `slo-generator` CLI directly

```
DEBUG: 0
Traceback (most recent call last):
  File "/usr/local/bin/slo-generator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/slo_generator/cli.py", line 32, in main
    cli(args)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/cli.py", line 65, in cli
    reports = compute(slo_config,
  File "/usr/local/lib/python3.8/site-packages/slo_generator/compute.py", line 52, in compute
    report = SLOReport(config=slo_config,
  File "/usr/local/lib/python3.8/site-packages/slo_generator/report.py", line 84, in __init__
    result = self.run_backend(config, client=client, delete=delete)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/report.py", line 175, in run_backend
    result = method(self.timestamp, self.window, config)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/backends/prometheus.py", line 88, in good_bad_ratio
    res_good = self.query(expr_good)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/backends/prometheus.py", line 117, in query
    response = json.loads(response)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 10 (char 9)
```

**Comment by svenmueller** [comment]
When we add a dummy key `project_id` in the Terrfaform SLO configuration template,  we can execute the plan/apply step. But now we see an issue when the cloud-function gets triggered and runs `slo-generator` to generate the report, we see the following issue in the log evens ("unexpected keyword argument 'project_id'"):

```
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 402, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 222, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 219, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 46, in main do_export=True) File "/env/local/lib/python3.7/site-packages/slo_generator/compute.py", line 56, in compute delete=delete) File "/env/local/lib/python3.7/site-packages/slo_generator/report.py", line 84, in __init__ result = self.run_backend(config, client=client, delete=delete) File "/env/local/lib/python3.7/site-packages/slo_generator/report.py", line 163, in run_backend instance = utils.get_backend_cls(cls)(client=client, **backend_cfg) TypeError: __init__() got an unexpected keyword argument 'project_id'
```

**Comment by ocervell** [comment]
Ah okay, so the PR above will fix that too, a new minor version will be released sometimes tomorrow or Thursday including other updates as well.

**Comment by ocervell** [comment]
@svenmueller the new version 0.2.1 is released. You won't need the `project_id` in the YAML's backend section anymore and it should work okay. Let me know !
